# Jitsu custom docker image
# See: https://jitsu.com/docs/deployment/deploy-with-docker/jitsu-server
# We're using a fixed version so we can control the upgrades and migration process
# Reference: https://hub.docker.com/r/jitsucom/server/
FROM jitsucom/server:1.44.7
COPY ./jitsu.yaml /home/eventnative/data/config/eventnative.yaml
